### ISSUE TITLE
remove git history

### ISSUE THREAD

**Issue by PatrickJS** [manavsehgal/AngularPages#2]

**Comment by manavsehgal** [comment]
sorry have not been active on this for a while. Will remove on next commit for sure.

**Comment by PatrickJS** [comment]
keep me updated. We (Angular 2 Universal) are looking to work a project for github pages so if you find the time we could use your help there

**Comment by manavsehgal** [comment]
@gdi2290 Sounds interesting about Angular 2 Universal for Github Pages. Please let me know where to sign up.

**Comment by manavsehgal** [comment]
Done. Removed commit history.
